#INITIAL SETTINGS
data_dir: ../data/
raw_data_dir: data\raw
processed_data_dir: data\processed
models_dir: models
raw_data_file_Macro_Economic: MacroEconomicData.xlsx
raw_data_file_Events_Holiday: Events_HolidaysData.xlsx
raw_data_file_Weather: WeatherData.xlsx 
raw_data_file_Sales: Train.csv
processed_data_file_1: Merged_data.csv
processed_data_file: processed_data.csv
training_model: TunedXGB_Model-v1.pkl
prediction_model: TunedXGB_Model-v1.pkl