#INITIAL SETTINGS
data_dir: ../data/
raw_data_dir: data\raw
processed_data_dir: data\processed
models_dir: models
raw_data_file_Macro_Economic: MacroEconomicData.xlsx
raw_data_file_Events_Holiday: Events_HolidaysData.xlsx
raw_data_file_Weather: WeatherData.xlsx 
raw_data_file_Sales: Train.csv
processed_data_file_1: Merged_data.csv
processed_data_file: processed_data.csv
training_model: Updated_TunedXGB_Model.pkl
prediction_model: Updated_TunedXGB_Model.pkl


#database configuration

db_config :
 DRIVER : 'SQL Server'
 SERVER : 'cr-devopsassessment.database.windows.net'          
 DATABASE : 'ml-usecases-db'
 UID: 'crmlteam'
 PWD : 'P455w0rd@123'
 PORT : '1433'